name: Release Workflow

on:
  release:
    types: [created, prereleased, published]

env:
  REPO: you54f/traveling-ruby
  PKG_DATE: 20241122
  NEXT_TAG: ${{ github.event.release.tag_name }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # Job to handle pre-release tasks
  prerelease:
    if: github.event.release.prerelease == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && apt update && apt install gh -y

      - name: Create Draft Release
        run: |
          RELEASE_NOTES=$(git log --pretty=format:"%s" $(git describe --tags --abbrev=0)..HEAD)
          gh release create "${NEXT_TAG}" --prerelease --draft --repo "${REPO}" --title "${NEXT_TAG}" --notes "${RELEASE_NOTES}"

  # Job to upload binaries
  upload-binaries:
    needs: prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload Binaries
        run: |
          cd linux
          for file in $(find traveling-ruby-gems-* -name '*.gz'); do
            gem_name=$(echo "${file%-*}" | tr '/' '-')
            gem_version=$(echo "${file%.tar.gz}" | awk -F- '{print $NF}')
            pkg_date=$(echo "${file%-*}" | cut -d'-' -f4)
            ruby_version=$(echo "${file%-*}" | tr '/' '-' | sed -E 's/.*-([0-9]+\.[0-9]+\.[0-9]+(-[a-z0-9]+)?)-([a-z]+)-([a-z0-9_]+)\.tar\.gz/\1/')
            echo $ruby_version-$gem_version.tar.gz
            cp "$file" $ruby_version-$gem_version.tar.gz
          done
          gh release upload "${NEXT_TAG}" traveling-ruby-*.tar.gz --repo "${REPO}" --clobber

  # Job to test the release
  test-release:
    needs: upload-binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y ruby

      - name: Download Release Binaries
        run: |
          gh release download "${NEXT_TAG}" --repo "${REPO}" -p "traveling-ruby-${PKG_DATE}*"
          tar -xzf traveling-ruby-${PKG_DATE}*

      - name: Run Tests
        run: |
          echo "Testing release binaries..."
          # Add your test commands here
          ruby --version
